/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICollectionVaultFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createVault" | "getVaults"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createVault', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getVaults', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaults', data: BytesLike): Result;
  }

  

  export interface ICollectionVaultFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICollectionVaultFactory;
    waitForDeployment(): Promise<this>;

    interface: ICollectionVaultFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createVault: TypedContractMethod<
      [name: string, symbol: string, ],
      [string],
      'nonpayable'
    >
    

    
    getVaults: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createVault'): TypedContractMethod<
      [name: string, symbol: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getVaults'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;

    

    filters: {
      
    };
  }