/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollectionVault } from './ICollectionVault.js';
export type { ICollectionVaultFactory } from './ICollectionVaultFactory.js';
export type { INFTCollectionFactory } from './INFTCollectionFactory.js';
export type { INFTMarketplace } from './INFTMarketplace.js';