/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace INFTMarketplace {
      
    export type ListingStruct = {seller: AddressLike, paymentToken: AddressLike, price: BigNumberish, isActive: boolean}

    export type ListingStructOutput = [seller: string, paymentToken: string, price: bigint, isActive: boolean] & {seller: string, paymentToken: string, price: bigint, isActive: boolean }
  
    }

  export interface INFTMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "buy" | "cancelListing" | "getListing" | "list" | "listOwnedNFT" | "setAuthorizedLister" | "setMarketplaceFee" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Cancelled" | "Listed" | "Purchased"): EventFragment;

    encodeFunctionData(functionFragment: 'buy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'list', values: [AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listOwnedNFT', values: [AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAuthorizedLister', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMarketplaceFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'list', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listOwnedNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedLister', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarketplaceFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace CancelledEvent {
      export type InputTuple = [nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [nftContract: string, tokenId: bigint, seller: string];
      export interface OutputObject {nftContract: string, tokenId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListedEvent {
      export type InputTuple = [nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, paymentToken: AddressLike, price: BigNumberish];
      export type OutputTuple = [nftContract: string, tokenId: bigint, seller: string, paymentToken: string, price: bigint];
      export interface OutputObject {nftContract: string, tokenId: bigint, seller: string, paymentToken: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PurchasedEvent {
      export type InputTuple = [nftContract: AddressLike, tokenId: BigNumberish, seller: AddressLike, buyer: AddressLike, price: BigNumberish];
      export type OutputTuple = [nftContract: string, tokenId: bigint, seller: string, buyer: string, price: bigint];
      export interface OutputObject {nftContract: string, tokenId: bigint, seller: string, buyer: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INFTMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): INFTMarketplace;
    waitForDeployment(): Promise<this>;

    interface: INFTMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buy: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getListing: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [INFTMarketplace.ListingStructOutput],
      'view'
    >
    

    
    list: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, paymentToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    listOwnedNFT: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, paymentToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedLister: TypedContractMethod<
      [lister: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMarketplaceFee: TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, ],
      [INFTMarketplace.ListingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'list'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, paymentToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listOwnedNFT'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, paymentToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedLister'): TypedContractMethod<
      [lister: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMarketplaceFee'): TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Cancelled'): TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
getEvent(key: 'Listed'): TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
getEvent(key: 'Purchased'): TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;

    filters: {
      
      'Cancelled(address,uint256,address)': TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
      Cancelled: TypedContractEvent<CancelledEvent.InputTuple, CancelledEvent.OutputTuple, CancelledEvent.OutputObject>;
    

      'Listed(address,uint256,address,address,uint256)': TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
      Listed: TypedContractEvent<ListedEvent.InputTuple, ListedEvent.OutputTuple, ListedEvent.OutputObject>;
    

      'Purchased(address,uint256,address,address,uint256)': TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
      Purchased: TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
    
    };
  }